language: node_js
node_js:
  - "8"

env:
  - DIR=demo
  - DIR=api

script:
  - cd $DIR
  - npm install
  - if [ "$DIR" = "demo" ] ; then npm run build ; fi
  - if [ "$DIR" = "api" ] ; then mkdir uploads ; fi
  - npm test
